from typing import Any, Dict
from langgraph.graph import StateGraph
from .news_workflow_model import NewsArticleState, build_news_article_graph


class NewsArticleWorkflowAgent:
    """Agent wrapper around the news article workflow graph."""

    def __init__(self):
        self.graph = None

    def compile(self):
        """Build the LangGraph workflow."""
        self.graph = build_news_article_graph()

    async def ainvoke(self, input_data: Dict[str, Any], thread_id: str = None):
        """Run the workflow asynchronously (currently synchronous execution)."""
        print("=== ainvoke (NEWS) received input_data ===")
        print(input_data)

        """Run the workflow asynchronously (currently synchronous execution)."""
        try:
            # 🧠 Extract input fields from frontend
            # These keys match the output of your 'normalize_news_input' function
            state = NewsArticleState(
                prompt=input_data.get("prompt", ""),
                additional_context=input_data.get("additional_context", ""),
                word_count=input_data.get("word_count", 800),
                tone=input_data.get("tone", ""),
                audience=input_data.get("audience", ""),
                
                # Ensure other keys required by NewsArticleState have defaults
                # (based on the model file we just wrote)
                research_notes="",
                article_draft="",
                compliance_report="",
                revision_count=0,
                final_response="",
            )

            # ⚙️ Run the LangGraph workflow
            graph = self.graph or build_news_article_graph()
            app = graph.compile()
            
            # 'result' will be the final state dictionary after the graph finishes
            result = app.invoke(state) 

            # Extract the final article from the final state
            article = result.get("article_draft", "No article was generated by the agent.")

            return {
                "status": "success",
                "data": {
                    # This is the key your news_router.py is looking for
                    "article_draft": article,
                    "raw_result": result  # optional: full workflow output
                }
            }

        except Exception as e:
            print(f"Error in NewsArticleWorkflowAgent: {e}")
            return {
                "status": "error",
                "message": str(e)
            }
